# Diff Drive + Joint State Broadcaster
joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    publish_rate: 50

diff_drive_base_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: false
    left_wheel_names: ["chassis_to_lf_wheel","chassis_to_lb_wheel"]
    right_wheel_names: ["chassis_to_rf_wheel","chassis_to_rb_wheel"]
    wheel_separation: 0.25   # adjust based on your robot
    wheel_radius: 0.06        # adjust based on URDF
    cmd_vel_timeout: 0.5
    publish_rate: 50
    enable_odom_tf: true
