---
controller_manager:
  ros__parameters:
    update_rate: 200
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: position_controllers/JointGroupPositionController

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['chassis_to_lf_wheel', 'chassis_to_lb_wheel']
    right_wheel_names: ['chassis_to_rf_wheel', 'chassis_to_rb_wheel']
    wheel_separation: 0.325
    wheel_radius: 0.06

    use_stamped_vel: true

arm_controller:
  ros__parameters:
    joints:
      - chassis_to_arm1
      - chassis_to_arm2
