---
controller_manager:
  ros__parameters:
    update_rate: 200
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

diff_cont:
  ros__parameters:

    publish_rate: 50.0

    base_frame_id: base_link

    left_wheel_names: ['chassis_to_lf_wheel', 'chassis_to_lb_wheel']
    right_wheel_names: ['chassis_to_rf_wheel', 'chassis_to_rb_wheel']
    wheel_separation: 0.6
    wheel_radius: 0.06

    use_stamped_vel: true

arm_controller:
  ros__parameters:
    joints:
      - chassis_to_arm1
      - chassis_to_arm2

    command_interfaces:
      - position

    state_interfaces:
      - position
      - velocity

    constraints:
      goal_time: 0.5
      stopped_velocity_tolerance: 0.01

    gains:
      chassis_to_arm1: {p: 100.0, d: 1.0, i: 0.0}
      chassis_to_arm2: {p: 100.0, d: 1.0, i: 0.0}
